AllCops:
  Exclude:
    - Rakefile
    - spec/**/*
    - vendor/**/*
  TargetRubyVersion: 2.0

# double quotes preferred, except in require
Style/StringLiterals:
  Enabled: false
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# appropriate hash formatting varies wildly
Style/MultilineMethodCallBraceLayout:
  Enabled: false
Style/AlignHash:
  Enabled: false

# aids readability
Style/RedundantSelf:
  Enabled: false
Style/ExtraSpacing:
  Enabled: false
Style/SpaceInsideBrackets:
  Enabled: false
Style/SpaceInsidePercentLiteralDelimiters:
  Enabled: false
Style/SpaceAroundEqualsInParameterDefault:
  Enabled: false
Style/SingleLineBlockParams:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/Alias:
  Enabled: false
Style/EmptyLinesAroundClassBody:
  Enabled: false
Style/EmptyLinesAroundModuleBody:
  Enabled: false
Style/IndentAssignment:
  Enabled: false

# sufficient length for modern screens
Metrics/LineLength:
  Max: 120

# {} distinguishes delimiters from method calls
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': '{}'

# self-documentation preferred
Style/Documentation:
  Enabled: false

# conditionals should contain statements
Style/EmptyElse:
  EnforcedStyle: empty
